// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenGame.Data;

namespace SenGame.Migrations
{
    [DbContext(typeof(SenGameContext))]
    [Migration("20220624153748_test123456")]
    partial class test123456
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SqlModels.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<string>("ArticleContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleTagID")
                        .HasComment("種類:討論、心得");

                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<DateTime>("LastReplyTime")
                        .HasColumnType("datetime")
                        .HasComment("最後回文時間");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime")
                        .HasComment("發文日期");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ArticleId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleLike", b =>
                {
                    b.Property<int>("LikeId")
                        .HasColumnType("int")
                        .HasColumnName("LikeID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LikeId")
                        .HasName("PK_Like");

                    b.ToTable("ArticleLike");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleTagID");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("ArticleTagId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("SqlModels.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    b.Property<string>("ChatContent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聊天紀錄");

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime")
                        .HasComment("現在聊天時間");

                    b.Property<string>("PictureFile")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("暫定");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasComment("使用者自身");

                    b.HasKey("ChatId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("SqlModels.Models.CustomerService", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date");

                    b.Property<int>("MyGameId")
                        .HasColumnType("int")
                        .HasColumnName("MyGameID");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("CustomerService");
                });

            modelBuilder.Entity("SqlModels.Models.Forum", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ForumId");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("SqlModels.Models.FriendGroup", b =>
                {
                    b.Property<int>("FriendGoupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FriendGoupId");

                    b.ToTable("FriendGroup");
                });

            modelBuilder.Entity("SqlModels.Models.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .HasColumnType("int")
                        .HasColumnName("FriendLIstId");

                    b.Property<int?>("FriendGroupId")
                        .HasColumnType("int");

                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.Property<string>("FriendNickName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<bool?>("IsBlockade")
                        .HasColumnType("bit")
                        .HasComment("是否被封鎖");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FriendListId");

                    b.ToTable("FriendList");
                });

            modelBuilder.Entity("SqlModels.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("開發商家");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DownTime")
                        .HasColumnType("datetime")
                        .HasComment("商品下架日期");

                    b.Property<string>("GameDetailsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("遊戲詳細介紹");

                    b.Property<string>("GameIntroduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("遊戲簡介");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GamePrice")
                        .HasColumnType("money");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("開發者");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime")
                        .HasComment("發布日期");

                    b.Property<int?>("TotalBuyCount")
                        .HasColumnType("int")
                        .HasComment("此遊戲被購買次數");

                    b.HasKey("GameId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SqlModels.Models.GameDiscount", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<double>("DiscountTake")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StarTime")
                        .HasColumnType("datetime");

                    b.HasKey("DiscountId");

                    b.ToTable("GameDiscount");
                });

            modelBuilder.Entity("SqlModels.Models.GameMedium", b =>
                {
                    b.Property<int>("GameMediaId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Instruction")
                        .HasColumnType("int")
                        .HasComment("1.圖片2.影片");

                    b.Property<int>("InstructionType")
                        .HasColumnType("int")
                        .HasComment("1幻燈片.2.簡介3.內文");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.HasKey("GameMediaId");

                    b.ToTable("GameMedia");
                });

            modelBuilder.Entity("SqlModels.Models.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("TypelistId")
                        .HasColumnType("int");

                    b.HasKey("GameTypeId");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("SqlModels.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasComment("邀請者");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("被邀請者");

                    b.HasKey("InviteId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("SqlModels.Models.MyFavouriteId", b =>
                {
                    b.Property<int>("MyFavouriteId1")
                        .HasColumnType("int")
                        .HasColumnName("MyFavouriteId");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("MyFavouriteId1");

                    b.ToTable("MyFavouriteId");
                });

            modelBuilder.Entity("SqlModels.Models.MyForum", b =>
                {
                    b.Property<int>("MyForumId")
                        .HasColumnType("int")
                        .HasColumnName("MyForumID");

                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MyForumId");

                    b.ToTable("MyForum");
                });

            modelBuilder.Entity("SqlModels.Models.MyGame", b =>
                {
                    b.Property<int>("MyGameId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("MyFavouriteId")
                        .HasColumnType("int")
                        .HasComment("我的最愛");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MyGameId");

                    b.ToTable("MyGame");
                });

            modelBuilder.Entity("SqlModels.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單時間");

                    b.Property<int>("EcpayId")
                        .HasColumnType("int")
                        .HasComment("Ecpay訂單編號");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true)
                        .HasComment("發票編碼");

                    b.Property<string>("InvoiceWay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true)
                        .HasComment("1.電子發票2.載具3.捐贈");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasComment("1.購物車 2.待付款  3.付款完成  4.申請退款 5.退款完成");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單更新時間");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SqlModels.Models.Orderdetail", b =>
                {
                    b.Property<int>("OrderdetailId")
                        .HasColumnType("int");

                    b.Property<double?>("Discount")
                        .HasColumnType("float")
                        .HasComment("訂單當時折購");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("OrderdetailId");

                    b.ToTable("Orderdetails");
                });

            modelBuilder.Entity("SqlModels.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID")
                        .HasComment("回復文章的回覆的回覆");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("SqlModels.Models.ReplyLike", b =>
                {
                    b.Property<int>("ReplyLikeId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyLikeID");

                    b.Property<int>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyLikeId");

                    b.ToTable("ReplyLike");
                });

            modelBuilder.Entity("SqlModels.Models.ServiceReply", b =>
                {
                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("客服回應");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.ToTable("ServiceReply");
                });

            modelBuilder.Entity("SqlModels.Models.SystemSpecification", b =>
                {
                    b.Property<int>("SystemSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Hddspace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HDDspace")
                        .HasComment("硬碟使用空間");

                    b.Property<string>("System")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("系統類別");

                    b.Property<string>("SystemCpu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("處理器");

                    b.Property<string>("SystemGpu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("顯示卡");

                    b.Property<string>("SystemRam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("記憶體");

                    b.Property<int>("SystemType")
                        .HasColumnType("int")
                        .HasComment("1:windows 2:Mac");

                    b.HasKey("SystemSpecificationId");

                    b.ToTable("SystemSpecification");
                });

            modelBuilder.Entity("SqlModels.Models.Typelist", b =>
                {
                    b.Property<int>("TypelistId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypelistId");

                    b.ToTable("Typelist");
                });

            modelBuilder.Entity("SqlModels.Models.UserBackground", b =>
                {
                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserBackgroundId");

                    b.ToTable("UserBackground");
                });

            modelBuilder.Entity("SqlModels.Models.UserCountry", b =>
                {
                    b.Property<int>("UserCountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserCountryId");

                    b.ToTable("UserCountry");
                });

            modelBuilder.Entity("SqlModels.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PrivacyFriendsList")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyGameFile")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPersonalFile")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserAbout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCountryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SqlModels.Models.UserPrivacy", b =>
                {
                    b.Property<int>("UserPrivacyId")
                        .HasColumnType("int");

                    b.Property<string>("PrivacyState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("隱私狀況");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPrivacyId");

                    b.ToTable("UserPrivacy");
                });

            modelBuilder.Entity("SqlModels.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishId");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
