// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenGame.Models;

namespace SenGame.Migrations
{
    [DbContext(typeof(SenGameContext))]
    [Migration("20220621115326_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<string>("ArticleContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleTagID")
                        .HasComment("種類:討論、心得");

                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<DateTime>("LastReplyTime")
                        .HasColumnType("date")
                        .HasComment("最後回文時間");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("date")
                        .HasComment("發文日期");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleTagId");

                    b.HasIndex("ForumId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SenGame.Models.ArticleLike", b =>
                {
                    b.Property<int>("LikeId")
                        .HasColumnType("int")
                        .HasColumnName("LikeID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LikeId")
                        .HasName("PK_Like");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleLike");
                });

            modelBuilder.Entity("SenGame.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleTagID");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("ArticleTagId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SenGame.Models.Blockade", b =>
                {
                    b.Property<int>("BlockadeId")
                        .HasColumnType("int")
                        .HasColumnName("BlockadeID");

                    b.Property<string>("BlockadeUserId")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("BlockadeUserID")
                        .IsFixedLength(true)
                        .HasComment("被封鎖人之ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BlockadeId");

                    b.HasIndex("UserId");

                    b.ToTable("Blockade");
                });

            modelBuilder.Entity("SenGame.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    b.Property<string>("ChatContent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聊天紀錄");

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("date")
                        .HasComment("現在聊天時間");

                    b.Property<string>("FriendId")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("FriendID")
                        .IsFixedLength(true);

                    b.Property<DateTime>("LastChatDate")
                        .HasColumnType("date")
                        .HasComment("最後聊天時間");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasComment("使用者自身");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("SenGame.Models.CustomerService", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date");

                    b.Property<int>("MyGameId")
                        .HasColumnType("int")
                        .HasColumnName("MyGameID");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.HasIndex("MyGameId");

                    b.ToTable("CustomerService");
                });

            modelBuilder.Entity("SenGame.Models.Forum", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ForumId");

                    b.HasIndex("GameId");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("SenGame.Models.FriendGroup", b =>
                {
                    b.Property<int>("FriendGoupId")
                        .HasColumnType("int")
                        .HasColumnName("FriendGoupID");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FriendGoupId");

                    b.ToTable("FriendGroup");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .HasColumnType("int")
                        .HasColumnName("FriendLIstID");

                    b.Property<int?>("FriendGroupId")
                        .HasColumnType("int")
                        .HasColumnName("FriendGroupID");

                    b.Property<int>("FriendId")
                        .HasColumnType("int")
                        .HasColumnName("FriendID");

                    b.Property<string>("FriendNickName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<bool?>("IsBlockade")
                        .HasColumnType("bit")
                        .HasComment("是否被封鎖");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FriendListId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("FriendList");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<string>("GameDetailsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameIntroduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GamePrice")
                        .HasColumnType("money");

                    b.Property<int>("GameTypleId")
                        .HasColumnType("int")
                        .HasColumnName("GameTypleID");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date")
                        .HasComment("發布日期");

                    b.Property<int?>("TotalBuyCount")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("GameTypleId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SenGame.Models.GameDiscount", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<double>("DiscountTake")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StarDate")
                        .HasColumnType("date");

                    b.HasKey("DiscountId");

                    b.ToTable("GameDiscount");
                });

            modelBuilder.Entity("SenGame.Models.GamePicture", b =>
                {
                    b.Property<int>("GamePictureId")
                        .HasColumnType("int")
                        .HasColumnName("GamePictureID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID")
                        .HasComment("是甚麼影片");

                    b.Property<string>("Instructions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("用途");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GamePictureId");

                    b.ToTable("GamePicture");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .HasColumnType("int")
                        .HasColumnName("GameTypeID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("TypelistId")
                        .HasColumnType("int")
                        .HasColumnName("TypelistID");

                    b.HasKey("GameTypeId");

                    b.HasIndex("TypelistId");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("SenGame.Models.GameVideo", b =>
                {
                    b.Property<int>("GameVideoId")
                        .HasColumnType("int")
                        .HasColumnName("GameVideoID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Instructions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameVideoId");

                    b.ToTable("GameVideo");
                });

            modelBuilder.Entity("SenGame.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .HasColumnType("int")
                        .HasColumnName("InviteID");

                    b.Property<string>("Message")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderID")
                        .HasComment("邀請者");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasComment("被邀請者");

                    b.HasKey("InviteId");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("SenGame.Models.MemderReply", b =>
                {
                    b.Property<int>("MemderReplyId")
                        .HasColumnType("int")
                        .HasColumnName("MemderReplyID");

                    b.Property<int>("FriendId")
                        .HasColumnType("int")
                        .HasColumnName("FriendID")
                        .HasComment("好友才能去主頁留言");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID")
                        .HasComment("判斷回復的回覆");

                    b.Property<string>("ReplyContent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("date")
                        .HasComment("留言當下時間");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MemderReplyId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("MemderReply");
                });

            modelBuilder.Entity("SenGame.Models.MyForum", b =>
                {
                    b.Property<int>("MyForumId")
                        .HasColumnType("int")
                        .HasColumnName("MyForumID");

                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MyForumId");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("MyForum");
                });

            modelBuilder.Entity("SenGame.Models.MyGame", b =>
                {
                    b.Property<int>("MyGameId")
                        .HasColumnType("int")
                        .HasColumnName("MyGameID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MyGameId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("MyGame");
                });

            modelBuilder.Entity("SenGame.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date")
                        .HasComment("訂單時間");

                    b.Property<int>("EcpayId")
                        .HasColumnType("int")
                        .HasColumnName("EcpayID")
                        .HasComment("Ecpay訂單編號");

                    b.Property<string>("Invoice")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("invoice")
                        .IsFixedLength(true)
                        .HasComment("發票票");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("OrderStatusID")
                        .HasComment("訂單單狀態");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SenGame.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("OrderStatusID");

                    b.Property<string>("StatusName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasComment("狀態");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("SenGame.Models.Orderdetail", b =>
                {
                    b.Property<int>("OrderdetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderdetailID");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("OrderdetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("Orderdetails");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID")
                        .HasComment("回復文章的回覆的回覆");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("SenGame.Models.ReplyLike", b =>
                {
                    b.Property<int>("ReplyLikeId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyLikeID");

                    b.Property<int>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyLikeId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("ReplyLike");
                });

            modelBuilder.Entity("SenGame.Models.ServiceReply", b =>
                {
                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("客服回應");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceReply");
                });

            modelBuilder.Entity("SenGame.Models.SystemSpecification", b =>
                {
                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<string>("Hddspace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HDDspace")
                        .HasComment("硬碟使用空間");

                    b.Property<string>("System")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("系統類別");

                    b.Property<string>("SystemRam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("記憶體");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SystemTypeID");

                    b.HasKey("SystemId");

                    b.HasIndex("GameId");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("SystemSpecification");
                });

            modelBuilder.Entity("SenGame.Models.SystemType", b =>
                {
                    b.Property<int>("SystmTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SystmTypeID");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SystmTypeId");

                    b.ToTable("SystemType");
                });

            modelBuilder.Entity("SenGame.Models.Typelist", b =>
                {
                    b.Property<int>("TypelistId")
                        .HasColumnType("int")
                        .HasColumnName("TypelistID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("TypelistId");

                    b.ToTable("Typelist");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAbout")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("自介");

                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int")
                        .HasColumnName("UserBackgroundID");

                    b.Property<int?>("UserCountryId")
                        .HasColumnType("int")
                        .HasColumnName("UserCountryID");

                    b.Property<string>("UserPicture")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UsernickName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.HasIndex("UserBackgroundId");

                    b.HasIndex("UserCountryId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SenGame.Models.UserBackground", b =>
                {
                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int")
                        .HasColumnName("UserBackgroundID");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserBackgroundId");

                    b.ToTable("UserBackground");
                });

            modelBuilder.Entity("SenGame.Models.UserCountry", b =>
                {
                    b.Property<int>("UserCountryId")
                        .HasColumnType("int")
                        .HasColumnName("UserCountryID");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserCountryId");

                    b.ToTable("UserCountry");
                });

            modelBuilder.Entity("SenGame.Models.UserEdit", b =>
                {
                    b.Property<int>("UserEditId")
                        .HasColumnType("int")
                        .HasColumnName("UserEditID")
                        .HasComment("");

                    b.Property<int>("FriendsList")
                        .HasColumnType("int")
                        .HasComment("好友名單");

                    b.Property<int?>("GameFile")
                        .HasColumnType("int")
                        .HasComment("遊戲資料");

                    b.Property<int>("PersonalFile")
                        .HasColumnType("int")
                        .HasComment("個人檔案");

                    b.Property<int>("ReplyName")
                        .HasColumnType("int")
                        .HasComment("是否能回復於個人主頁");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserEditId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEdit");
                });

            modelBuilder.Entity("SenGame.Models.UserPrivacy", b =>
                {
                    b.Property<int>("UserPrivacyId")
                        .HasColumnType("int")
                        .HasColumnName("UserPrivacyID");

                    b.Property<string>("PrivacyState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("隱私狀況");

                    b.Property<int>("UserEditId")
                        .HasColumnType("int")
                        .HasColumnName("UserEditID");

                    b.HasKey("UserPrivacyId");

                    b.HasIndex("UserEditId");

                    b.ToTable("UserPrivacy");
                });

            modelBuilder.Entity("SenGame.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .HasColumnType("int")
                        .HasColumnName("WishID");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("date");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("WishId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.HasOne("SenGame.Models.ArticleTag", "ArticleTag")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleTagId")
                        .HasConstraintName("FK_Article_ArticleTag")
                        .IsRequired();

                    b.HasOne("SenGame.Models.Forum", "Forum")
                        .WithMany("Articles")
                        .HasForeignKey("ForumId")
                        .HasConstraintName("FK_Article_Forum")
                        .IsRequired();

                    b.Navigation("ArticleTag");

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("SenGame.Models.ArticleLike", b =>
                {
                    b.HasOne("SenGame.Models.Article", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_Like_Article")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Like_User")
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("SenGame.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserRole", b =>
                {
                    b.HasOne("SenGame.Models.AspNetRole", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserToken", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Blockade", b =>
                {
                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Blockades")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Blockade_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Chat", b =>
                {
                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Chat_User")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.CustomerService", b =>
                {
                    b.HasOne("SenGame.Models.MyGame", "MyGame")
                        .WithMany("CustomerServices")
                        .HasForeignKey("MyGameId")
                        .HasConstraintName("FK_CustomerService_MyGame")
                        .IsRequired();

                    b.Navigation("MyGame");
                });

            modelBuilder.Entity("SenGame.Models.Forum", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("Forums")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Forum_Game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.HasOne("SenGame.Models.User", "Friend")
                        .WithMany("FriendListFriends")
                        .HasForeignKey("FriendId")
                        .HasConstraintName("FK_FriendList_User1")
                        .IsRequired();

                    b.HasOne("SenGame.Models.FriendGroup", "FriendListNavigation")
                        .WithOne("FriendList")
                        .HasForeignKey("SenGame.Models.FriendList", "FriendListId")
                        .HasConstraintName("FK_FriendList_FriendGroup")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("FriendListUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FriendList_User")
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("FriendListNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.HasOne("SenGame.Models.GameDiscount", "Discount")
                        .WithMany("Games")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Game_GameDiscount")
                        .IsRequired();

                    b.HasOne("SenGame.Models.GameType", "GameTyple")
                        .WithMany("Games")
                        .HasForeignKey("GameTypleId")
                        .HasConstraintName("FK_Game_GameType")
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("GameTyple");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.HasOne("SenGame.Models.Typelist", "Typelist")
                        .WithMany("GameTypes")
                        .HasForeignKey("TypelistId")
                        .HasConstraintName("FK_GameType_Typelist")
                        .IsRequired();

                    b.Navigation("Typelist");
                });

            modelBuilder.Entity("SenGame.Models.Invite", b =>
                {
                    b.HasOne("SenGame.Models.User", "Sender")
                        .WithMany("InviteSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Invite_User1")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("InviteUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Invite_User")
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.MemderReply", b =>
                {
                    b.HasOne("SenGame.Models.FriendList", "Friend")
                        .WithMany("MemderReplies")
                        .HasForeignKey("FriendId")
                        .HasConstraintName("FK_MemderReply_FriendList")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("MemderReplies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MemderReply_User")
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.MyForum", b =>
                {
                    b.HasOne("SenGame.Models.Forum", "Forum")
                        .WithMany("MyForums")
                        .HasForeignKey("ForumId")
                        .HasConstraintName("FK_MyForum_Forum")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("MyForums")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyForum_User")
                        .IsRequired();

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.MyGame", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("MyGames")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_MyGame_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("MyGames")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyGame_User")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Order", b =>
                {
                    b.HasOne("SenGame.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .HasConstraintName("FK_Order_OrderStatus")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Order_User")
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Orderdetail", b =>
                {
                    b.HasOne("SenGame.Models.Order", "Order")
                        .WithMany("Orderdetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Orderdetails_Order")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.HasOne("SenGame.Models.Article", "Article")
                        .WithMany("Replies")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_Reply_Article")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reply_User")
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.ReplyLike", b =>
                {
                    b.HasOne("SenGame.Models.Reply", "Reply")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FK_ReplyLike_Reply")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ReplyLike_User")
                        .IsRequired();

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.ServiceReply", b =>
                {
                    b.HasOne("SenGame.Models.CustomerService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_ServiceReply_CustomerService")
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SenGame.Models.SystemSpecification", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_SystemSpecification_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.SystemType", "SystemType")
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("SystemTypeId")
                        .HasConstraintName("FK_SystemSpecification_SystemType")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.HasOne("SenGame.Models.UserBackground", "UserBackground")
                        .WithMany("Users")
                        .HasForeignKey("UserBackgroundId")
                        .HasConstraintName("FK_User_UserBackground")
                        .IsRequired();

                    b.HasOne("SenGame.Models.UserCountry", "UserCountry")
                        .WithMany("Users")
                        .HasForeignKey("UserCountryId")
                        .HasConstraintName("FK_User_UserCountry");

                    b.Navigation("UserBackground");

                    b.Navigation("UserCountry");
                });

            modelBuilder.Entity("SenGame.Models.UserEdit", b =>
                {
                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("UserEdits")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserEdit_User")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.UserPrivacy", b =>
                {
                    b.HasOne("SenGame.Models.UserEdit", "UserEdit")
                        .WithMany("UserPrivacies")
                        .HasForeignKey("UserEditId")
                        .HasConstraintName("FK_UserPrivacy_UserEdit")
                        .IsRequired();

                    b.Navigation("UserEdit");
                });

            modelBuilder.Entity("SenGame.Models.Wish", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("Wishes")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Wish_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Wishes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Wish_User")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.Navigation("ArticleLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SenGame.Models.ArticleTag", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("SenGame.Models.Forum", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("MyForums");
                });

            modelBuilder.Entity("SenGame.Models.FriendGroup", b =>
                {
                    b.Navigation("FriendList");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.Navigation("MemderReplies");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.Navigation("Forums");

                    b.Navigation("MyGames");

                    b.Navigation("SystemSpecifications");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("SenGame.Models.GameDiscount", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SenGame.Models.MyGame", b =>
                {
                    b.Navigation("CustomerServices");
                });

            modelBuilder.Entity("SenGame.Models.Order", b =>
                {
                    b.Navigation("Orderdetails");
                });

            modelBuilder.Entity("SenGame.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.Navigation("ReplyLikes");
                });

            modelBuilder.Entity("SenGame.Models.SystemType", b =>
                {
                    b.Navigation("SystemSpecifications");
                });

            modelBuilder.Entity("SenGame.Models.Typelist", b =>
                {
                    b.Navigation("GameTypes");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.Navigation("ArticleLikes");

                    b.Navigation("Blockades");

                    b.Navigation("Chats");

                    b.Navigation("FriendListFriends");

                    b.Navigation("FriendListUsers");

                    b.Navigation("InviteSenders");

                    b.Navigation("InviteUsers");

                    b.Navigation("MemderReplies");

                    b.Navigation("MyForums");

                    b.Navigation("MyGames");

                    b.Navigation("Orders");

                    b.Navigation("Replies");

                    b.Navigation("ReplyLikes");

                    b.Navigation("UserEdits");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("SenGame.Models.UserBackground", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SenGame.Models.UserCountry", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SenGame.Models.UserEdit", b =>
                {
                    b.Navigation("UserPrivacies");
                });
#pragma warning restore 612, 618
        }
    }
}
