// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenGame.Models;

namespace SenGame.Migrations
{
    [DbContext(typeof(SenGameContext))]
    partial class SenGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<string>("Check")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ArticleId");

                    b.HasIndex("GameId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SenGame.Models.Chat", b =>
                {
                    b.Property<int>("Chatid")
                        .HasColumnType("int");

                    b.Property<string>("ChatContext")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ChatDate")
                        .HasColumnType("date");

                    b.Property<int?>("FriendListId")
                        .HasColumnType("int")
                        .HasColumnName("FriendListID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Chatid");

                    b.HasIndex("FriendListId");

                    b.HasIndex("UserId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .HasColumnType("int")
                        .HasColumnName("FriendListID");

                    b.Property<bool>("BlockadeList")
                        .HasColumnType("bit");

                    b.Property<int?>("FriendId")
                        .HasColumnType("int")
                        .HasColumnName("FriendID");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FriendListId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("FriendList");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<string>("GameDetailsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameIntroduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GamePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GamePrice")
                        .HasColumnType("money");

                    b.Property<int>("GameTypleId")
                        .HasColumnType("int")
                        .HasColumnName("GameTypleID");

                    b.Property<string>("GameVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseDataId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseDataID");

                    b.Property<DateTime?>("ReleadeDate")
                        .HasColumnType("date");

                    b.Property<string>("SystemGraphCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SystemMemory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SystemOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemUseSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TotalBuyCount")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("GameTypleId");

                    b.HasIndex("PurchaseDataId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SenGame.Models.GameDiscount", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<int?>("DiscountTake")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StarDate")
                        .HasColumnType("date");

                    b.HasKey("DiscountId");

                    b.ToTable("GameDiscount");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .HasColumnType("int")
                        .HasColumnName("GameTypeID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("TypelistId")
                        .HasColumnType("int")
                        .HasColumnName("TypelistID");

                    b.HasKey("GameTypeId");

                    b.HasIndex("TypelistId");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("SenGame.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .HasColumnType("int")
                        .HasColumnName("InviteID");

                    b.Property<string>("Message")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<int>("SendId")
                        .HasColumnType("int")
                        .HasColumnName("SendID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("InviteId");

                    b.HasIndex("SendId");

                    b.HasIndex("UserId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("SenGame.Models.Like", b =>
                {
                    b.Property<int>("LikeId")
                        .HasColumnType("int")
                        .HasColumnName("LikeID");

                    b.Property<int>("Article")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LikeId");

                    b.HasIndex("Article");

                    b.HasIndex("UserId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("SenGame.Models.MyForum", b =>
                {
                    b.Property<int>("MyForumId")
                        .HasColumnType("int")
                        .HasColumnName("MyForumID");

                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MyForumId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("MyForum");
                });

            modelBuilder.Entity("SenGame.Models.MyGame", b =>
                {
                    b.Property<int>("MyGameId")
                        .HasColumnType("int")
                        .HasColumnName("MyGameID");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MyGameId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("MyGame");
                });

            modelBuilder.Entity("SenGame.Models.PurchaseDatum", b =>
                {
                    b.Property<int>("PurchaseDataId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseDataID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("PurchaseDataId");

                    b.ToTable("PurchaseData");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<string>("ReplyMain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("SenGame.Models.ReplyLike", b =>
                {
                    b.Property<int>("ReplyLikeId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyLikeID");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("int")
                        .HasColumnName("ReplyID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReplyLikeId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("ReplyLike");
                });

            modelBuilder.Entity("SenGame.Models.Typelist", b =>
                {
                    b.Property<int>("TypelistId")
                        .HasColumnType("int")
                        .HasColumnName("TypelistID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("TypelistId");

                    b.ToTable("Typelist");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWordTest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayId")
                        .HasColumnType("int")
                        .HasColumnName("PayID");

                    b.Property<int?>("UserCountryId")
                        .HasColumnType("int")
                        .HasColumnName("UserCountryID");

                    b.Property<string>("UserPicture")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserUrl")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("UsernickName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.HasIndex("PayId");

                    b.HasIndex("UserCountryId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SenGame.Models.UserCountry", b =>
                {
                    b.Property<int>("UserCountryId")
                        .HasColumnType("int")
                        .HasColumnName("UserCountryID");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserCountryId");

                    b.ToTable("UserCountry");
                });

            modelBuilder.Entity("SenGame.Models.Visa", b =>
                {
                    b.Property<int>("PayId")
                        .HasColumnType("int")
                        .HasColumnName("PayID");

                    b.Property<string>("VisaCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisaDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VisaSaft")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength(true);

                    b.HasKey("PayId");

                    b.ToTable("Visa");
                });

            modelBuilder.Entity("SenGame.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .HasColumnType("int")
                        .HasColumnName("WishID");

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("date");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("WishId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("Articles")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Article_Game")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("SenGame.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserRole", b =>
                {
                    b.HasOne("SenGame.Models.AspNetRole", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUserToken", b =>
                {
                    b.HasOne("SenGame.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Chat", b =>
                {
                    b.HasOne("SenGame.Models.FriendList", "FriendList")
                        .WithMany("Chats")
                        .HasForeignKey("FriendListId")
                        .HasConstraintName("FK_Chat_FriendList");

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Chat_User");

                    b.Navigation("FriendList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.HasOne("SenGame.Models.User", "Friend")
                        .WithMany("FriendListFriends")
                        .HasForeignKey("FriendId")
                        .HasConstraintName("FK_FriendList_User1");

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("FriendListUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FriendList_User")
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.HasOne("SenGame.Models.GameDiscount", "Discount")
                        .WithMany("Games")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Game_GameDiscount")
                        .IsRequired();

                    b.HasOne("SenGame.Models.GameType", "GameTyple")
                        .WithMany("Games")
                        .HasForeignKey("GameTypleId")
                        .HasConstraintName("FK_Game_GameType")
                        .IsRequired();

                    b.HasOne("SenGame.Models.PurchaseDatum", "PurchaseData")
                        .WithMany("Games")
                        .HasForeignKey("PurchaseDataId")
                        .HasConstraintName("FK_Game_PurchaseData");

                    b.Navigation("Discount");

                    b.Navigation("GameTyple");

                    b.Navigation("PurchaseData");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.HasOne("SenGame.Models.Typelist", "Typelist")
                        .WithMany("GameTypes")
                        .HasForeignKey("TypelistId")
                        .HasConstraintName("FK_GameType_Typelist")
                        .IsRequired();

                    b.Navigation("Typelist");
                });

            modelBuilder.Entity("SenGame.Models.Invite", b =>
                {
                    b.HasOne("SenGame.Models.User", "Send")
                        .WithMany("InviteSends")
                        .HasForeignKey("SendId")
                        .HasConstraintName("FK_Invite_User1")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("InviteUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Invite_User")
                        .IsRequired();

                    b.Navigation("Send");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Like", b =>
                {
                    b.HasOne("SenGame.Models.Article", "ArticleNavigation")
                        .WithMany("Likes")
                        .HasForeignKey("Article")
                        .HasConstraintName("FK_Like_Article")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Like_User")
                        .IsRequired();

                    b.Navigation("ArticleNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.MyForum", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("MyForums")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_MyForum_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("MyForums")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyForum_User")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.MyGame", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("MyGames")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_MyGame_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("MyGames")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyGame_User")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.HasOne("SenGame.Models.Article", "Article")
                        .WithMany("Replies")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_Reply_Article")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reply_User")
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.ReplyLike", b =>
                {
                    b.HasOne("SenGame.Models.Reply", "Reply")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FK_ReplyLike_Reply");

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ReplyLike_User");

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.HasOne("SenGame.Models.Visa", "Pay")
                        .WithMany("Users")
                        .HasForeignKey("PayId")
                        .HasConstraintName("FK_User_Visa")
                        .IsRequired();

                    b.HasOne("SenGame.Models.UserCountry", "UserCountry")
                        .WithMany("Users")
                        .HasForeignKey("UserCountryId")
                        .HasConstraintName("FK_User_UserCountry");

                    b.Navigation("Pay");

                    b.Navigation("UserCountry");
                });

            modelBuilder.Entity("SenGame.Models.Wish", b =>
                {
                    b.HasOne("SenGame.Models.Game", "Game")
                        .WithMany("Wishes")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Wish_Game")
                        .IsRequired();

                    b.HasOne("SenGame.Models.User", "User")
                        .WithMany("Wishes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Wish_User")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SenGame.Models.Article", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SenGame.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("SenGame.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("SenGame.Models.FriendList", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("SenGame.Models.Game", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("MyForums");

                    b.Navigation("MyGames");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("SenGame.Models.GameDiscount", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SenGame.Models.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SenGame.Models.PurchaseDatum", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("SenGame.Models.Reply", b =>
                {
                    b.Navigation("ReplyLikes");
                });

            modelBuilder.Entity("SenGame.Models.Typelist", b =>
                {
                    b.Navigation("GameTypes");
                });

            modelBuilder.Entity("SenGame.Models.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("FriendListFriends");

                    b.Navigation("FriendListUsers");

                    b.Navigation("InviteSends");

                    b.Navigation("InviteUsers");

                    b.Navigation("Likes");

                    b.Navigation("MyForums");

                    b.Navigation("MyGames");

                    b.Navigation("Replies");

                    b.Navigation("ReplyLikes");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("SenGame.Models.UserCountry", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SenGame.Models.Visa", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
