// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlModels.Data;

namespace SqlModels.Migrations
{
    [DbContext(typeof(SenGameContext))]
    partial class SenGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SqlModels.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int")
                        .HasComment("種類:討論、心得");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReplyTime")
                        .HasColumnType("datetime")
                        .HasComment("最後回文時間");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime")
                        .HasComment("發文日期");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleTagId");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleLike", b =>
                {
                    b.Property<int>("LikeId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LikeId")
                        .HasName("PK_Like");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleLike");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleTagId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("ArticleTagId");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex1")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRole");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId")
                        .HasDatabaseName("IX_AspNetRoleClaims_RoleId1");

                    b.ToTable("AspNetRoleClaim");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PrivacyFriendsList")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyGameFile")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPersonalFile")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserAbout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCountryId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserBackgroundId");

                    b.HasIndex("UserCountryId");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex")
                        .HasDatabaseName("EmailIndex1");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex1")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUser");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId")
                        .HasDatabaseName("IX_AspNetUserClaims_UserId1");

                    b.ToTable("AspNetUserClaim");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId")
                        .HasDatabaseName("IX_AspNetUserLogins_UserId1");

                    b.ToTable("AspNetUserLogin");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId")
                        .HasDatabaseName("IX_AspNetUserRoles_RoleId1");

                    b.ToTable("AspNetUserRole");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserToken");
                });

            modelBuilder.Entity("SqlModels.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("ChatContent")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("聊天紀錄");

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime")
                        .HasComment("現在聊天時間");

                    b.Property<string>("PictureFile")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("暫定");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("使用者自身");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("SqlModels.Models.CustomerService", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("date");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("GameId");

                    b.ToTable("CustomerService");
                });

            modelBuilder.Entity("SqlModels.Models.Ecpay", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MerchantID")
                        .HasComment("特店編號,Ecpa提供");

                    b.Property<int>("ChoosePayment")
                        .HasColumnType("int")
                        .HasComment("1.Criedit 2. ATM");

                    b.Property<string>("ClientBackUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientBackURL")
                        .HasComment("返回指定網頁");

                    b.Property<int>("ExpireDate")
                        .HasColumnType("int")
                        .HasComment("允許繳費有效天數");

                    b.Property<string>("HashIv")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("HashIV")
                        .IsFixedLength(true);

                    b.Property<string>("HashKey")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true);

                    b.Property<string>("ReturnUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ReturnURL")
                        .HasComment("付款完成\r\n通知回傳\r\n網址");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("更新資訊時間");

                    b.HasKey("MerchantId");

                    b.ToTable("Ecpay");
                });

            modelBuilder.Entity("SqlModels.Models.Forum", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<string>("Banner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ForumId");

                    b.HasIndex("GameId");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("SqlModels.Models.FriendGroup", b =>
                {
                    b.Property<int>("FriendGoupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("FriendGoupId");

                    b.ToTable("FriendGroup");
                });

            modelBuilder.Entity("SqlModels.Models.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .HasColumnType("int")
                        .HasColumnName("FriendLIstId");

                    b.Property<int?>("FriendGroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBlockade")
                        .HasColumnType("bit")
                        .HasComment("是否被封鎖");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FriendListId");

                    b.HasIndex("UserId");

                    b.ToTable("FriendList");
                });

            modelBuilder.Entity("SqlModels.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("開發商家");

                    b.Property<DateTime?>("DownTime")
                        .HasColumnType("datetime")
                        .HasComment("商品下架日期");

                    b.Property<string>("GameDetailsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("遊戲詳細介紹");

                    b.Property<string>("GameIntroduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("遊戲簡介");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GamePrice")
                        .HasColumnType("money");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("開發者");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("datetime")
                        .HasComment("發布日期");

                    b.Property<int?>("TotalBuyCount")
                        .HasColumnType("int")
                        .HasComment("此遊戲被購買次數");

                    b.HasKey("GameId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SqlModels.Models.GameDiscount", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<double>("DiscountTake")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StarTime")
                        .HasColumnType("datetime");

                    b.HasKey("DiscountId");

                    b.HasIndex("GameId");

                    b.ToTable("GameDiscount");
                });

            modelBuilder.Entity("SqlModels.Models.GameMedium", b =>
                {
                    b.Property<int>("GameMediaId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Instruction")
                        .HasColumnType("int")
                        .HasComment("1.圖片2.影片");

                    b.Property<int>("InstructionType")
                        .HasColumnType("int")
                        .HasComment("1幻燈片.2.簡介3.內文");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.HasKey("GameMediaId");

                    b.HasIndex("GameId");

                    b.ToTable("GameMedia");
                });

            modelBuilder.Entity("SqlModels.Models.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("TypelistId")
                        .HasColumnType("int");

                    b.HasKey("GameTypeId");

                    b.HasIndex("GameId");

                    b.HasIndex("TypelistId");

                    b.ToTable("GameType");
                });

            modelBuilder.Entity("SqlModels.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasComment("邀請者");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("被邀請者");

                    b.HasKey("InviteId");

                    b.HasIndex("UserId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("SqlModels.Models.MyFavouriteId", b =>
                {
                    b.Property<int>("MyFavouriteId1")
                        .HasColumnType("int")
                        .HasColumnName("MyFavouriteId");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("MyFavouriteId1");

                    b.ToTable("MyFavouriteId");
                });

            modelBuilder.Entity("SqlModels.Models.MyForum", b =>
                {
                    b.Property<int>("MyForumId")
                        .HasColumnType("int");

                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<int?>("Sort")
                        .HasColumnType("int")
                        .HasComment("看板排序");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MyForumId");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("MyForum");
                });

            modelBuilder.Entity("SqlModels.Models.MyGame", b =>
                {
                    b.Property<int>("MyGameId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("MyFavourite")
                        .HasColumnType("bit")
                        .HasComment("判別是否是我的最愛");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MyGameId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("MyGame");
                });

            modelBuilder.Entity("SqlModels.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單取消時間");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單時間");

                    b.Property<string>("EcpayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Ecpay訂單編號");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true)
                        .HasComment("發票編碼");

                    b.Property<string>("InvoiceWay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true)
                        .HasComment("1.電子發票2.載具3.捐贈");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasComment("1.待付款  3.付款完成  4.申請退款 5.退款完成");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("TradeTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單成立時間");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasComment("訂單更新時間");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SqlModels.Models.Orderdetail", b =>
                {
                    b.Property<int>("OrderdetailId")
                        .HasColumnType("int");

                    b.Property<double?>("Discount")
                        .HasColumnType("float")
                        .HasComment("購買後則顯示當時折扣");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("OrderdetailId");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("Orderdetails");
                });

            modelBuilder.Entity("SqlModels.Models.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasComment("回復文章的回覆的回覆");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReplyId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("SqlModels.Models.ReplyLike", b =>
                {
                    b.Property<int>("ReplyLikeId")
                        .HasColumnType("int");

                    b.Property<int>("ReplyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReplyLikeId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("ReplyLike");
                });

            modelBuilder.Entity("SqlModels.Models.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("SqlModels.Models.SystemSpecification", b =>
                {
                    b.Property<int>("SystemSpecificationId")
                        .HasColumnType("int");

                    b.Property<int?>("Configure")
                        .HasColumnType("int")
                        .HasComment("1.最低配備 2.建議配備");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Hddspace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HDDspace")
                        .HasComment("硬碟使用空間");

                    b.Property<string>("System")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("系統類別");

                    b.Property<string>("SystemCpu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("處理器");

                    b.Property<string>("SystemGpu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("顯示卡");

                    b.Property<string>("SystemRam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("記憶體");

                    b.Property<int>("SystemType")
                        .HasColumnType("int")
                        .HasComment("1:windows 2:Mac");

                    b.HasKey("SystemSpecificationId");

                    b.HasIndex("GameId");

                    b.ToTable("SystemSpecification");
                });

            modelBuilder.Entity("SqlModels.Models.Typelist", b =>
                {
                    b.Property<int>("TypelistId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypelistId");

                    b.ToTable("Typelist");
                });

            modelBuilder.Entity("SqlModels.Models.UserBackground", b =>
                {
                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserBackgroundId");

                    b.ToTable("UserBackground");
                });

            modelBuilder.Entity("SqlModels.Models.UserCountry", b =>
                {
                    b.Property<int>("UserCountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserCountryId");

                    b.ToTable("UserCountry");
                });

            modelBuilder.Entity("SqlModels.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EmailConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PrivacyFriendsList")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyGameFile")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPersonalFile")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserAbout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserBackgroundId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCountryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SqlModels.Models.UserPrivacy", b =>
                {
                    b.Property<int>("UserPrivacyId")
                        .HasColumnType("int");

                    b.Property<string>("PrivacyState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("隱私狀況");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPrivacyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPrivacy");
                });

            modelBuilder.Entity("SqlModels.Models.Usergroup", b =>
                {
                    b.Property<int>("FriendGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("FriendGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Usergroup");
                });

            modelBuilder.Entity("SqlModels.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishId");

                    b.HasIndex("GameId");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SqlModels.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SqlModels.Models.Article", b =>
                {
                    b.HasOne("SqlModels.Models.ArticleTag", "ArticleTag")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleTagId")
                        .HasConstraintName("FK_Article_ArticleTag")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.Forum", "Forum")
                        .WithMany("Articles")
                        .HasForeignKey("ForumId")
                        .HasConstraintName("FK_Article_Forum")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Article_AspNetUsers")
                        .IsRequired();

                    b.Navigation("ArticleTag");

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleLike", b =>
                {
                    b.HasOne("SqlModels.Models.Article", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_ArticleLike_Article")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ArticleLike_AspNetUsers")
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUser", b =>
                {
                    b.HasOne("SqlModels.Models.Order", "Order")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_AspNetUsers_Order");

                    b.HasOne("SqlModels.Models.UserBackground", "UserBackground")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("UserBackgroundId")
                        .HasConstraintName("FK_AspNetUsers_UserBackground")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.UserCountry", "UserCountry")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("UserCountryId")
                        .HasConstraintName("FK_AspNetUsers_UserCountry");

                    b.Navigation("Order");

                    b.Navigation("UserBackground");

                    b.Navigation("UserCountry");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUserRole", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetRole", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SqlModels.Models.Chat", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Chat_AspNetUsers")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.CustomerService", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("CustomerServices")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_CustomerService_Game")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.Forum", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("Forums")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Forum_Game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.FriendList", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("FriendLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FriendList_AspNetUsers")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.GameDiscount", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("GameDiscounts")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_GameDiscount_Game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.GameMedium", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("GameMedia")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_GameMedia_Game")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.GameType", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("GameTypes")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_GameType_Game")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.Typelist", "Typelist")
                        .WithMany("GameTypes")
                        .HasForeignKey("TypelistId")
                        .HasConstraintName("FK_GameType_Typelist");

                    b.Navigation("Game");

                    b.Navigation("Typelist");
                });

            modelBuilder.Entity("SqlModels.Models.Invite", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("Invites")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Invite_AspNetUsers")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.MyForum", b =>
                {
                    b.HasOne("SqlModels.Models.Forum", "Forum")
                        .WithMany("MyForums")
                        .HasForeignKey("ForumId")
                        .HasConstraintName("FK_MyForum_Forum")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("MyForums")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyForum_AspNetUsers")
                        .IsRequired();

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.MyGame", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("MyGames")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_MyGame_Game")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("MyGames")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MyGame_AspNetUsers")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.Orderdetail", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("Orderdetails")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Orderdetails_Game")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.Order", "Order")
                        .WithMany("Orderdetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Orderdetails_Order")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SqlModels.Models.Reply", b =>
                {
                    b.HasOne("SqlModels.Models.Article", "Article")
                        .WithMany("Replies")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("FK_Reply_Article")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reply_AspNetUsers")
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.ReplyLike", b =>
                {
                    b.HasOne("SqlModels.Models.Reply", "Reply")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FK_ReplyLike_Reply")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("ReplyLikes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ReplyLike_AspNetUsers")
                        .IsRequired();

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.ShoppingCart", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_ShoppingCart_Game");

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ShoppingCart_AspNetUsers");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.SystemSpecification", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_SystemSpecification_Game")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.UserPrivacy", b =>
                {
                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany("UserPrivacies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserPrivacy_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.Usergroup", b =>
                {
                    b.HasOne("SqlModels.Models.FriendGroup", "FriendGroup")
                        .WithMany()
                        .HasForeignKey("FriendGroupId")
                        .HasConstraintName("FK_Usergroup_FriendGroup")
                        .IsRequired();

                    b.HasOne("SqlModels.Models.AspNetUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Usergroup_AspNetUsers")
                        .IsRequired();

                    b.Navigation("FriendGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlModels.Models.Wish", b =>
                {
                    b.HasOne("SqlModels.Models.Game", "Game")
                        .WithMany("Wishes")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Wish_Game")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SqlModels.Models.Article", b =>
                {
                    b.Navigation("ArticleLikes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SqlModels.Models.ArticleTag", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("SqlModels.Models.AspNetUser", b =>
                {
                    b.Navigation("ArticleLikes");

                    b.Navigation("Articles");

                    b.Navigation("Chats");

                    b.Navigation("FriendLists");

                    b.Navigation("Invites");

                    b.Navigation("MyForums");

                    b.Navigation("MyGames");

                    b.Navigation("Replies");

                    b.Navigation("ReplyLikes");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("UserPrivacies");
                });

            modelBuilder.Entity("SqlModels.Models.Forum", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("MyForums");
                });

            modelBuilder.Entity("SqlModels.Models.Game", b =>
                {
                    b.Navigation("CustomerServices");

                    b.Navigation("Forums");

                    b.Navigation("GameDiscounts");

                    b.Navigation("GameMedia");

                    b.Navigation("GameTypes");

                    b.Navigation("MyGames");

                    b.Navigation("Orderdetails");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("SystemSpecifications");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("SqlModels.Models.Order", b =>
                {
                    b.Navigation("AspNetUsers");

                    b.Navigation("Orderdetails");
                });

            modelBuilder.Entity("SqlModels.Models.Reply", b =>
                {
                    b.Navigation("ReplyLikes");
                });

            modelBuilder.Entity("SqlModels.Models.Typelist", b =>
                {
                    b.Navigation("GameTypes");
                });

            modelBuilder.Entity("SqlModels.Models.UserBackground", b =>
                {
                    b.Navigation("AspNetUsers");
                });

            modelBuilder.Entity("SqlModels.Models.UserCountry", b =>
                {
                    b.Navigation("AspNetUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
